# Generated by Django 5.2.16 on 2026-07-30 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="名称")),
                (
                    "engine",
                    models.CharField(
                        choices=[("mysql", "MySQL"), ("postgresql", "PostgreSQL"), ("sqlite", "SQLite")],
                        max_length=20,
                        verbose_name="引擎类型",
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255, verbose_name="主机")),
                ("port", models.IntegerField(blank=True, null=True, verbose_name="端口")),
                ("database", models.CharField(max_length=255, verbose_name="数据库/文件路径")),
                ("username", models.CharField(blank=True, default="", max_length=128, verbose_name="用户名")),
                ("password_encrypted", models.TextField(blank=True, default="", verbose_name="加密密码")),
                ("group", models.CharField(blank=True, default="default", max_length=64, verbose_name="分组")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源",
                "ordering": ["-id"],
            },
        ),
    ]
