preset           = "strict"
project-excludes = [".venv/**", "template/**", "frontend/**", "backend/db/**", "backend/staticfiles/**"]
project-includes = ["**/*.ipynb", "**/*.py*"]
python-version   = "3.10"
search-path      = ["backend"]
