[tox]
isolated_build = true
envlist = py310, py311, py312, py313
min_version = 4.0
requires = tox-uv
skipsdist = true

[testenv]
uv_sync = true
deps =
    pytest>=8.0.0
    pytest-django>=4.8
    pytest-cov>=5.0.0
    pytest-html>=4.1.1
    pytest-xdist>=3.6.1
commands =
    pytest -m "not slow" {posargs}
passenv =
    CI
    GITHUB_*
    UV_*
    PYTHON*
setenv =
    PYTHONPATH = {toxinidir}/backend
    PYTHONDONTWRITEBYTECODE = 1
