# Generated by Django 5.2.16 on 2026-08-08 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="任务名称")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="描述")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("api", "REST/JSON API"),
                            ("html", "网页 HTML"),
                            ("file", "文件下载"),
                            ("rss", "RSS/Atom"),
                        ],
                        max_length=20,
                        verbose_name="源类型",
                    ),
                ),
                ("source_url", models.URLField(max_length=1024, verbose_name="源 URL")),
                ("parse_config", models.JSONField(blank=True, default=dict, verbose_name="解析配置")),
                ("request_config", models.JSONField(blank=True, default=dict, verbose_name="请求配置")),
                ("headers_encrypted", models.TextField(blank=True, default="", verbose_name="加密请求头")),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "无鉴权"),
                            ("api_key", "API Key"),
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("custom", "自定义"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="鉴权类型",
                    ),
                ),
                ("target_table", models.CharField(max_length=128, verbose_name="目标表名")),
                (
                    "conflict_strategy",
                    models.CharField(
                        choices=[("upsert", "冲突则更新"), ("skip", "冲突则跳过"), ("error", "冲突则报错")],
                        default="upsert",
                        max_length=20,
                        verbose_name="主键冲突处理策略",
                    ),
                ),
                ("batch_size", models.PositiveIntegerField(default=500, verbose_name="批量大小")),
                ("obey_robots", models.BooleanField(default=True, verbose_name="遵守 robots.txt")),
                ("scheduler_enabled", models.BooleanField(default=False, verbose_name="启用定时调度")),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Cron 表达式（如 */5 * * * * 表示每5分钟）"
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="上次执行时间")),
                ("next_run_at", models.DateTimeField(blank=True, null=True, verbose_name="下次执行时间")),
                ("retry_count", models.PositiveSmallIntegerField(default=0, verbose_name="已重试次数")),
                ("max_retries", models.PositiveSmallIntegerField(default=3, verbose_name="最大重试次数")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("paused", "暂停"), ("error", "错误")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True, verbose_name="最近爬取时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingest_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "target_datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_tasks",
                        to="datasources.datasource",
                        verbose_name="目标数据源",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取任务",
                "verbose_name_plural": "爬取任务",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="IngestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("partial", "部分成功"), ("failed", "失败")],
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                ("rows_read", models.PositiveIntegerField(default=0, verbose_name="读取行数")),
                ("rows_written", models.PositiveIntegerField(default=0, verbose_name="写入行数")),
                ("rows_skipped", models.PositiveIntegerField(default=0, verbose_name="跳过行数")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("duration_ms", models.PositiveIntegerField(default=0, verbose_name="耗时（毫秒）")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ingest.ingesttask",
                        verbose_name="爬取任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取日志",
                "verbose_name_plural": "爬取日志",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestFieldMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_field", models.CharField(max_length=128, verbose_name="源字段名")),
                ("target_field", models.CharField(max_length=128, verbose_name="目标字段名")),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[("direct", "直接映射"), ("constant", "常量")],
                        default="direct",
                        max_length=20,
                        verbose_name="映射类型",
                    ),
                ),
                (
                    "fixed_value",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="常量值（mapping_type=constant 时使用）"
                    ),
                ),
                ("is_pk", models.BooleanField(default=False, verbose_name="是否主键")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="ingest.ingesttask",
                        verbose_name="爬取任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取字段映射",
                "verbose_name_plural": "爬取字段映射",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="IngestAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "警告"), ("error", "错误")],
                        default="error",
                        max_length=20,
                        verbose_name="告警级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="告警内容")),
                ("acknowledged", models.BooleanField(default=False, verbose_name="是否已确认")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True, verbose_name="确认时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ingest.ingesttask",
                        verbose_name="爬取任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取告警",
                "verbose_name_plural": "爬取告警",
                "ordering": ["-created_at"],
            },
        ),
    ]
