# Generated by Django 5.2.16 on 2026-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingesttask",
            name="clean_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="清洗配置"),
        ),
        migrations.AddField(
            model_name="ingesttask",
            name="validation_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="校验配置"),
        ),
    ]
