# Generated by Django 5.2.16 on 2026-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfig',
            name='cron_expression',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Cron 表达式（如 */5 * * * * 表示每5分钟）'),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间'),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='最大重试次数'),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间'),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已重试次数'),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='scheduler_enabled',
            field=models.BooleanField(default=False, verbose_name='启用定时调度'),
        ),
    ]
