# Generated by Django 5.2.16 on 2026-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0002_add_scheduler_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncconfig",
            name="conflict_strategy",
            field=models.CharField(
                choices=[("upsert", "冲突则更新"), ("skip", "冲突则跳过"), ("error", "冲突则报错")],
                default="upsert",
                max_length=20,
                verbose_name="主键冲突处理策略",
            ),
        ),
    ]
