# Generated by Django 5.2.16 on 2026-08-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0003_syncconfig_conflict_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "警告"), ("error", "错误")],
                        default="error",
                        max_length=20,
                        verbose_name="告警级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="告警内容")),
                ("acknowledged", models.BooleanField(default=False, verbose_name="是否已确认")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True, verbose_name="确认时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="sync.syncconfig",
                        verbose_name="同步配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步告警",
                "verbose_name_plural": "同步告警",
                "ordering": ["-created_at"],
            },
        ),
    ]
