# Generated by Django 5.2.16 on 2026-07-31 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(blank=True, default="", max_length=150, verbose_name="用户名（冗余）")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("write", "写操作"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("datasource.create", "创建数据源"),
                            ("datasource.update", "更新数据源"),
                            ("datasource.delete", "删除数据源"),
                            ("draft.create", "创建草稿"),
                            ("draft.update", "更新草稿"),
                            ("draft.delete", "删除草稿"),
                            ("draft.rollback", "回滚版本"),
                            ("ddl.apply", "应用 DDL"),
                            ("dml.insert", "新增行"),
                            ("dml.update", "更新行"),
                            ("dml.delete", "删除行"),
                            ("dml.import", "导入数据"),
                            ("sql.execute", "执行 SQL"),
                            ("obj.alter", "编辑对象"),
                            ("obj.drop", "删除对象"),
                        ],
                        default="write",
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("middleware", "中间件"), ("business", "业务层")],
                        default="middleware",
                        max_length=16,
                        verbose_name="记录来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failure", "失败")],
                        default="success",
                        max_length=16,
                        verbose_name="操作结果",
                    ),
                ),
                ("method", models.CharField(blank=True, default="", max_length=8, verbose_name="HTTP 方法")),
                ("path", models.CharField(blank=True, default="", max_length=512, verbose_name="请求路径")),
                ("resource_type", models.CharField(blank=True, default="", max_length=64, verbose_name="资源类型")),
                ("resource_id", models.CharField(blank=True, default="", max_length=128, verbose_name="资源 ID")),
                ("datasource_id", models.IntegerField(blank=True, null=True, verbose_name="数据源 ID")),
                (
                    "datasource_name",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="数据源名称（冗余）"),
                ),
                ("sql", models.TextField(blank=True, default="", verbose_name="SQL 文本")),
                ("row_count", models.IntegerField(blank=True, null=True, verbose_name="影响行数")),
                ("elapsed_ms", models.IntegerField(blank=True, null=True, verbose_name="耗时（毫秒）")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="客户端 IP")),
                ("user_agent", models.CharField(blank=True, default="", max_length=512, verbose_name="User-Agent")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="扩展信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_audit_user"),
                    models.Index(fields=["action"], name="idx_audit_action"),
                    models.Index(fields=["datasource_id"], name="idx_audit_ds"),
                    models.Index(fields=["created_at"], name="idx_audit_created"),
                    models.Index(fields=["status"], name="idx_audit_status"),
                ],
            },
        ),
    ]
