# Generated by Django 5.2.16 on 2026-08-08 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_password_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Token 名称")),
                ("token_hash", models.CharField(max_length=64, unique=True, verbose_name="Token 哈希（SHA-256）")),
                ("prefix", models.CharField(max_length=16, verbose_name="Token 前缀（展示用）")),
                ("scopes", models.JSONField(blank=True, default=list, verbose_name="权限范围")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="过期时间")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="最后使用时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_by"], name="idx_apitoken_creator"),
                    models.Index(fields=["is_active"], name="idx_apitoken_active"),
                ],
            },
        ),
    ]
