# Generated by Django 5.2.16 on 2026-08-09 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="名称")),
                ("url", models.URLField(max_length=512, verbose_name="接收 URL")),
                ("secret", models.CharField(max_length=256, verbose_name="签名密钥")),
                (
                    "signing_algorithm",
                    models.CharField(
                        choices=[("sha256", "HMAC-SHA256")], default="sha256", max_length=16, verbose_name="签名算法"
                    ),
                ),
                ("events", models.JSONField(blank=True, default=list, verbose_name="订阅事件类型列表")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook 订阅",
                "verbose_name_plural": "Webhook 订阅",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDeliveryLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=64, verbose_name="事件类型")),
                ("payload", models.JSONField(default=dict, verbose_name="投递负载")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="HTTP 响应码")),
                ("retry_count", models.IntegerField(default=0, verbose_name="已重试次数")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="下次重试时间")),
                ("response_body", models.TextField(blank=True, default="", verbose_name="响应体（截断）")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("started_at", models.DateTimeField(verbose_name="开始投递时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束投递时间")),
                ("duration_ms", models.IntegerField(blank=True, null=True, verbose_name="耗时（毫秒）")),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhook.webhooksubscription",
                        verbose_name="订阅",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook 投递日志",
                "verbose_name_plural": "Webhook 投递日志",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhooksubscription",
            index=models.Index(fields=["is_active"], name="idx_webhook_sub_active"),
        ),
        migrations.AddIndex(
            model_name="webhookdeliverylog",
            index=models.Index(fields=["subscription"], name="idx_webhook_dl_sub"),
        ),
        migrations.AddIndex(
            model_name="webhookdeliverylog",
            index=models.Index(fields=["event_type"], name="idx_webhook_dl_event"),
        ),
        migrations.AddIndex(
            model_name="webhookdeliverylog",
            index=models.Index(fields=["started_at"], name="idx_webhook_dl_started"),
        ),
    ]
