# Generated by Django 5.2.16 on 2026-07-30 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="草稿名称")),
                ("table_name", models.CharField(max_length=128, verbose_name="目标表名")),
                ("schema_name", models.CharField(blank=True, default="", max_length=128, verbose_name="目标 schema")),
                ("spec", models.JSONField(default=dict, verbose_name="表设计规范")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("applied", "已应用")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_drafts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="datasources.datasource",
                        verbose_name="目标数据源",
                    ),
                ),
            ],
            options={
                "verbose_name": "表设计草稿",
                "verbose_name_plural": "表设计草稿",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DesignVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_no", models.PositiveIntegerField(verbose_name="版本号")),
                ("spec", models.JSONField(default=dict, verbose_name="版本快照")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="designer.designdraft",
                        verbose_name="所属草稿",
                    ),
                ),
            ],
            options={
                "verbose_name": "草稿版本",
                "verbose_name_plural": "草稿版本",
                "ordering": ["-version_no"],
            },
        ),
        migrations.AddConstraint(
            model_name="designdraft",
            constraint=models.UniqueConstraint(
                fields=("datasource", "table_name", "schema_name"), name="unique_draft_per_table"
            ),
        ),
        migrations.AddConstraint(
            model_name="designversion",
            constraint=models.UniqueConstraint(fields=("draft", "version_no"), name="unique_version_no_per_draft"),
        ),
    ]
